fix(Header): fix deployment errors
Failed to compile.
./src/app/Header/UpperRow/SearchResults.tsx
3:27  Error: Member 'useEffect' of the import declaration should be sorted alphabetically.  sort-imports
5:1  Warning: `@supabase/auth-helpers-nextjs` import should occur before import of `react`  import/order
35:8  Warning: React Hook useEffect has missing dependencies: 'searchProducts' and 'supabase'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
46:2  Error: Unnecessary semicolon.  @typescript-eslint/no-extra-semi
3:10  Warning: 'values' is defined but never used. Allowed unused vars must match /^_/u.  @typescript-eslint/no-unused-vars
18:41  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command "yarn run build" exited with 1